--- 
- name: Securing Mariadb
  hosts: db_servers
  become: true
  tasks:
    - name: Assign password to root
      mysql_user:
        user: root
        host_all: true
        update_password: always
        password: "{{ pw }}"

    - name: authentication credientials copied to root home directory
      copy:
        src: files/my.cnf
        dest: /root/.my.cnf

    - name: Remove anonymous user accounts
      mysql_user:
        name: ''
        host_all: true
        state: absent

    - name: removeing test database
      mysql_db:
        name: test
        state:absent